config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'inventories#index'

  
  resources :inventories do
    collection do
      get :stock_report
    end
  end


  resources :orders, only: %i[index show] do
    collection do
      get :add_to_cart
      get :remove_from_cart
    end
  end

  resources :purchases, except: %i[new create edit update destroy] do
    collection do
      get :generate_bill
      post :generate_purchase_report
      get :purchase_report
    end

    member do
      get :pay_bill
    end
  end

  resources :discounts
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :orders
  has_many :discounts, as: :entity
  validates :item_name, uniqueness: true

  UNITS_ARRAY = %w[kg l m pc].freeze
  CATEGORY_ARRAY = %w[vegetables fruits grocery beverages 
  	snacks toileteries].freeze

  def self.generate_stock_report
    Inventory.all
  end
end

app/controllers/inventories_controller.rb
# frozen_string_literal: true

# Responsible for CRUD operations for Inventories
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[show edit update destroy]

  def index
    @inventories = Inventory.all
    @user_role = current_user.role.name if current_user
  end

  def show; end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    if @inventory.save
      flash[:success] = 'Inventory was successfully created.'
      redirect_to @inventory
    else
      render :new
    end
  end

  def edit; end

  def update
    if @inventory.update(inventory_params)
      flash[:success] = 'Inventory was successfully updated.'
      redirect_to @inventory
    else
      render :edit
    end
  end

  def destroy
    if @inventory.destroy
      flash[:success] = 'Inventory was successfully destroyed.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to inventories_url
  end

  def stock_report
    @inventories = Inventory.generate_stock_report

  end

  private

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  def inventory_params
    params.require(:inventory).permit(:item_name, :category,
    :quantity_available, :unit, :cost_per_unit)
  end
end

app/helpers/inventories_helper.rb
# frozen_string_literal: true

module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory, local: true) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :item_name, id: :inventory_item_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, Inventory::CATEGORY_ARRAY %>
  </div>

  <div class="field">
    <%= form.label :quantity_available %>
    <%= form.number_field :quantity_available, id: :inventory_quantity_available %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.select :unit, Inventory::UNITS_ARRAY %>
  </div>

  <div class="field">
    <%= form.label :cost_per_unit %>
    <%= form.number_field :cost_per_unit, id: :inventory_cost_per_unit %>
  </div>

  <div class="actions">
    <%= form.submit class: 'action-btn' %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<div class='main-content'>
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>
</div>

app/views/inventories/index.html.erb
<div class='main-content'>

<div class="grid-container">

  <% @inventories.each do |inventory| %>
    <div class="grid-item" data-item-name="<%=inventory.item_name%>" data-maxquantity="<%=inventory.quantity_available%>">
      
      <p class="grid-p">Item: <%= inventory.item_name %></p>
      <p class="grid-p">Categeory: <%= inventory.category %></p>
      <p class="grid-p avail-quan">Available: <%= inventory.quantity_available %> <%= inventory.unit %></p><p class="hide avail-quan"><%= inventory.quantity_available %></p>
      <p class="grid-p"><%= inventory.cost_per_unit %></p>
      <p class="grid-p"><%= link_to 'Show', inventory %></p>
      <% if can? :edit, @inventory %>
      <% end %>  

      <% if @user_role == Role::ADMIN %> 
        <p class="grid-p"><%= link_to 'Edit', edit_inventory_path(inventory) %></p>
 
        <p class="grid-p"><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>

      <% if @user_role == Role::SHOPPER %>
        <p class="grid-p""><button class='add-to-cart'>Add to Cart</button>
        Quantity:    <input type="number" class="quantity" name="quantity" min="1" max="<%= inventory.quantity_available%>"><br>
        </p>
      <% end %> 
    </div>  
    <% end %>
</div>


<% if @user_role == Role::SHOPPER %>
  <%= link_to 'Place Order', generate_bill_purchases_path, class: 'action-btn' %>
<% end %>
</div>

app/views/inventories/new.html.erb
<div class='main-content'>

<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>
</div>

app/views/inventories/show.html.erb
<div class='main-content'>

<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @inventory.item_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @inventory.category %>
</p>

<p>
  <strong>Quantity available:</strong>
  <%= @inventory.quantity_available %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @inventory.unit %>
</p>

<p>
  <strong>Cost per unit:</strong>
  <%= @inventory.cost_per_unit %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>
</div>

app/views/inventories/stock_report.html.erb
<div class='main-content'>

<table>
	<tr>
		<th>Item Name</th>
		<th>Category</th>
		<th>Quantity</th>
		<th>Unit</th>
		<th>Cost Per Unit</th>
		<th>Actions</th>
	</tr>
  
  <% @inventories.each do |inventory| %>
		<tr>
			<td><%= inventory.item_name %></td>
			<td><%= inventory.category %></td>
			<td><%= inventory.quantity_available %></td>
			<td><%= inventory.unit %></td>
			<td><%= inventory.cost_per_unit %></td>
			<td><%= link_to 'Edit', edit_inventory_path(inventory.id) %><%= link_to 'Delete', inventory, method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
  <% end %>

</table>
</div>