config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'inventories#index'

  
  resources :inventories do
    collection do
      get :stock_report
    end
  end


  resources :orders, only: %i[index show] do
    collection do
      get :add_to_cart
      get :remove_from_cart
    end
  end

  resources :purchases, except: %i[new create edit update destroy] do
    collection do
      get :generate_bill
      post :generate_purchase_report
      get :purchase_report
    end

    member do
      get :pay_bill
    end
  end

  resources :discounts
end

app/controllers/purchases_controller.rb
# frozen_string_literal: true

# Responsible for Bill Generations and Report generations
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  def generate_bill
    @detailed_bill_hash = Purchase.generate_bill(current_user)
  end

  def pay_bill
    @purchase = Purchase.find(params[:id])

    if @purchase.update_attributes!(status: 'paid')
      status = 'success'
      message = 'Your bill paid successfully! You will receive your order soon'
    else
      status = 'Failure'
      message = 'Something went wrong !'
    end

    @response = { status: status, message: message }
  end

  def purchase_report
  end

  def generate_purchase_report
    @purchases_hash = Purchase.generate_purchase_report(params[:from],
                                                        params[:to])
  end
end

app/helpers/purchases_helper.rb
# frozen_string_literal: true

module PurchasesHelper
end

app/views/purchases/generate_bill.html.erb
<% if @detailed_bill_hash.present? %>

	<table class="bill">
		<tr>
			<th>Item</th>
			<th>Quantity</th>
			<th>Unit price</th>
			<th>Price</th>
		</tr>
	  
	  <% @detailed_bill_hash[:bill_items].each do |item| %>
			<tr>
				<td><%= item[:item_name] %></td>
				<td><%= item[:quantity] %></td>
				<td><%= item[:unit_price] %></td>
				<td><%= item[:item_price] %></td>
			</tr>
		<% end %>

		<tr>
			<td></td>
			<td>Total Amount</td>
			<td></td>
			<td><%= @detailed_bill_hash[:total_amount] %></td>
	</table>

	<%= link_to 'Pay Bill', pay_bill_purchase_path(id: @detailed_bill_hash[:purchase].id) %>

<% end %>

app/views/purchases/generate_purchase_report.html.erb
<div class='main-content'>


<table>
	<tr>
		<th>Bill Code</th>
		<th>Status</th>
		<th>Amount</th>
	</tr>
  
  <% @purchases_hash[:purchases].each do |purchase| %>
		<tr>
			<td><%= purchase.bill_code %></td>
			<td><%= purchase.status %></td>
			<td><%= purchase.total_amount %></td>
		</tr>
  <% end %>

	<tr>
		<td></td>
		<td>Total</td>
		<td><%= @purchases_hash[:total] %></td>
	</tr>	

</table>
</div>

app/views/purchases/pay_bill.html.erb
<table>
	<tr>
		<td><%= @purchase.bill_code %></td>
		<td><%= @purchase.total_amount %></td>
	</tr>

</table>

<% if @response[:status] == 'success' %>
	<div class="success">
<% else %>
	<div class="failure">
<% end %>

<p><%= @response[:message] %></p>

<p><%= link_to 'Buy More', root_path %></p>
</div>

app/views/purchases/purchase_report.html.erb
      <div class='main-content'>

            <%= form_tag "/purchases/generate_purchase_report" do %>
              <%= date_field_tag 'from', Date.today %>
              <%= date_field_tag 'to', Date.today %>

              <%= submit_tag 'Generate Purchase report' %>
            <% end %>

          </div>