config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'inventories#index'

  
  resources :inventories do
    collection do
      get :stock_report
    end
  end


  resources :orders, only: %i[index show] do
    collection do
      get :add_to_cart
      get :remove_from_cart
    end
  end

  resources :purchases, except: %i[new create edit update destroy] do
    collection do
      get :generate_bill
      post :generate_purchase_report
      get :purchase_report
    end

    member do
      get :pay_bill
    end
  end

  resources :discounts
end

app/models/discount.rb
# frozen_string_literal: true

class Discount < ApplicationRecord
  belongs_to :entity, polymorphic: true

  DISCOUNTABLE = { 'Role': ['Name'], 'Inventory': %w[ItemName Category] }.freeze
end

app/controllers/discounts_controller.rb
# frozen_string_literal: true

# Responsible for CRUD Operation for discounts Feature
class DiscountsController < ApplicationController
  before_action :set_discount, only: %i[show edit update destroy]

  before_action :authenticate_user!

  def index
    @discounts = Discount.all
  end

  def show
    @discount = Discount.find(params[:id])
  end

  def new
    @discount = Discount.new
    @discountable = Discount::DISCOUNTABLE
  end

  def create
    @discount = Discount.new(discount_params)

    if @discount.save
      flash[:success] = 'discount was successfully created.'
      redirect_to @discount
    else
      render :new
    end
  end

  def edit
    @discount = Discount.find(params[:id])
  end

  def update
    if @discount.update(discount_params)
      flash[:success] = 'discount was successfully updated.'
      redirect_to @discount
    else
      render :edit
    end
  end

  def destroy
    if @discount.destroy
      flash[:success] = 'discount was successfully destroyed.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to inventories_url
  end

  private

  def set_discount
    @discount = Discount.find(params[:id])
  end

  def discount_params
    params.require(:discount).permit(:name, :entity_id, 
    	:entity_type, :discount_field, :discount_condition, :value)
  end
end

app/helpers/discounts_helper.rb
# frozen_string_literal: true

module DiscountsHelper
end

app/views/discounts/_form.html.erb
<script type="text/javascript">
  var discountable = '<%= @discountable %>'
</script>

<%= form_with(model: discount, local: true) do |form| %>
  <% if discount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

      <ul>
      <% discount.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :entity_type %>
    <%= form.select :entity_type, ['Role', 'Inventory'] %>
  </div>

  <div class="field">
    <%= form.label :discount_field %>
    <%= form.select :discount_field, Role.all.collect { |u| [u.name, u.id] } %>
  </div>

  <div class="field">
    <%= form.label :discount_condition %>
    <%= form.select :discount_condition, [' ', '>', '<', 'equals'] %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value  %>
  </div>

  <div class="field">
    <%= form.label :discount_unit %>
    <%= form.select :discount_unit, ['Amount', 'Percentage']  %>
  </div>

  <div class="field">
    <%= form.label :discount_value %>
    <%= form.text_field :discount_value  %>
  </div>

  <div class="actions">
    <%= form.submit class: 'action-btn' %>
  </div>
<% end %>

app/views/discounts/index.html.erb
<table>
	<tr>
		<th>Name</th>
		<th>Type</th>
		<th>Discount Object</th>
		<th>Discount Field</th>
		<th>Discount Condition</th>
		<th>Value</th>
	</tr>

	<% @discounts.each do |discount| %>
		<tr>
			<td><%= discount.name %></td>
			<td><%= discount.entity.class %></td>
			<td><%= discount.entity.name %></td>
			<td><%= discount.discount_field %></td>
			<td><%= discount.discount_condition %></td>
			<td><%= discount.value %></td>
		</tr>
	<% end %>
</table>

<p><%= link_to 'Add Discount', new_discount_path %></p>
<p><%= link_to 'Buy More', root_path %></p>

app/views/discounts/new.html.erb
<h1>New Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Back', discounts_path %>